apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-app
    task: option1
  name: secret-app-svc
  namespace: secret-namespace
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30218
  selector:
    app: secret-app
  type: NodePort
