apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: secret-namespace-deploy-rolebinding
  namespace: secret-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-namespace-deploy-role
subjects:
- kind: ServiceAccount
  name: secret-namespace-deployment-sa
  namespace: secret-namespace