# This is a basic workflow to help you get started with Actions

name: Deploy to K8S

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
    branches: 
    - deployment-pipeline
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    name: "Deploy application"
    runs-on: ubuntu-latest
    environment: production
    env:
      WORK-DIR: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: checkout
        
      - name: Get image name to be scanned
        run: echo "IMAGE=$(cat deployment.yaml | yq \".spec.template.spec.containers[].image\")" >> $GITHUB_ENV
        
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "${{ env.IMAGE }}"
          fail-build: true
          severity-cutoff: high

      - name: create kube-config file
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d >> kube-config 

      # Runs a single command using the runners shell
      - name: Deploy apps
        run: kubectl apply --kubeconfig=kube-config  -f .

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
