# This is a basic workflow to help you get started with Actions

name: Deploy to K8S

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy application"
    runs-on: ubuntu-latest
    environment: production
    env:
      WORK-DIR: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: checkout
        
      - name: Get image name to be scanned
        run: echo "IMAGE=$(cat deployment.yaml | yq ".spec.template.spec.containers[].image")" >> $GITHUB_ENV
        
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "${{ env.IMAGE }}"
          fail-build: false
          severity-cutoff: high

      - name: create kube-config file
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d >> kube-config 

      # Runs a single command using the runners shell
      - name: Deploy apps
        run: kubectl apply --kubeconfig=kube-config  -f .

